apiVersion: apps/v1
kind: Deployment
metadata:
  name: krs-web-app
  labels:
    app: krs-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krs-web-app
  template:
    metadata:
      labels:
        app: krs-web-app
      annotations:
        # This tells Kubernetes to forcefully pull the fresh image tag on every rollout
        rollout-timestamp: "${date}"
    spec:
      containers:
      - name: web-app
        image: docker.io/oraclekrscloud/devops-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: krs-registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: krs-web-service
spec:
  selector:
    app: krs-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort
