name: CI Pipeline - Build & Push Container KRS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compile and Publish Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest
          no-cache: true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # <--- Crucial: Wait for the image to be completely on Docker Hub first
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: SSH into Rocky Linux VM and Execute Playbook
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: devopskrs
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/devopskrs/zero_cost_devops_pipeline_krs
            ansible-playbook deploy-prod.yml
